"""empty message

Revision ID: 2c9d65abe0c7
Revises: 20a7ca82c3df
Create Date: 2025-03-02 17:59:42.711402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c9d65abe0c7'
down_revision = '20a7ca82c3df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancel_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancel_reason', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('refund_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.drop_column('refund_status')
        batch_op.drop_column('cancel_reason')
        batch_op.drop_column('cancel_date')

    # ### end Alembic commands ###
