"""Fix table names and foreign key references

Revision ID: 5fff2d813f2a
Revises: 8cc580e0a727
Create Date: 2025-03-02 21:36:23.979133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fff2d813f2a'
down_revision = '8cc580e0a727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop the 'parcels' table first to avoid foreign key constraint issues
    op.drop_table('parcels')

    # Drop the 'users' table with CASCADE using raw SQL
    op.execute('DROP TABLE users CASCADE')

    # Create the new 'user' table
    op.create_table('user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=80), nullable=False),
        sa.Column('email', sa.String(length=120), nullable=False),
        sa.Column('password_hash', sa.String(length=128), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=False),
        sa.Column('reset_token', sa.String(length=32), nullable=True),
        sa.Column('email_notifications', sa.Boolean(), nullable=False),
        sa.Column('dark_mode', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username')
    )

    # Create the new 'item' table
    op.create_table('item',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('image_url', sa.String(length=200), nullable=False),
        sa.Column('rating', sa.Float(), nullable=True),
        sa.Column('price', sa.Float(), nullable=False),
        sa.Column('purchase_date', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Create the new 'parcel' table
    op.create_table('parcel',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tracking_id', sa.String(length=50), nullable=False),
        sa.Column('pickup_location', sa.String(length=200), nullable=False),
        sa.Column('destination', sa.String(length=200), nullable=False),
        sa.Column('distance', sa.Float(), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('current_location', sa.String(length=200), nullable=True),
        sa.Column('weight', sa.Float(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('cost', sa.Float(), nullable=True),
        sa.Column('delivery_speed', sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tracking_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop the new tables first
    op.drop_table('parcel')
    op.drop_table('item')
    op.drop_table('user')

    # Recreate the old 'users' table
    op.create_table('users',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
        sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
        sa.Column('password_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name='users_pkey'),
        sa.UniqueConstraint('email', name='users_email_key'),
        sa.UniqueConstraint('username', name='users_username_key')
    )

    # Recreate the old 'parcels' table
    op.create_table('parcels',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('tracking_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column('pickup_location', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column('destination', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column('current_location', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
        sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column('delivery_speed', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column('distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='parcels_user_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='parcels_pkey'),
        sa.UniqueConstraint('tracking_id', name='parcels_tracking_id_key')
    )
    # ### end Alembic commands ###