"""Add cost field to Parcel model

Revision ID: 9ec1bcb4ea2d
Revises: 2fe50edba20c
Create Date: 2025-02-21 17:25:13.031410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ec1bcb4ea2d'
down_revision = '2fe50edba20c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.drop_column('cost')

    # ### end Alembic commands ###
